### ISSUE TITLE
"No module named raven.contrib.flask" upon running tests

### ISSUE THREAD

**Issue by mark-henry** [imwilsonxu/fbone#65]
On osx:
1. Setup new python virtualenv
2. run pip install -r requirements.txt 
3. Setup with fab setup_python_macos
4. run unit tests with fab test

I saw:
Traceback (most recent call last):
  File "tests.py", line 6, in <module>
    from fbone import create_app
  File "/Users/mark.henry/Desktop/actionteam/fbone/__init__.py", line 3, in <module>
    from app import create_app
  File "/Users/mark.henry/Desktop/actionteam/fbone/app.py", line 6, in <module>
    from user import User
  File "/Users/mark.henry/Desktop/actionteam/fbone/user/__init__.py", line 3, in <module>
    from models import User
  File "/Users/mark.henry/Desktop/actionteam/fbone/user/models.py", line 10, in <module>
    from fbone.extensions import db
  File "/Users/mark.henry/Desktop/actionteam/fbone/extensions.py", line 10, in <module>
    from raven.contrib.flask import Sentry
ImportError: No module named raven.contrib.flask

**Comment by Amanimasila** [comment]
I still have error even after install  this module
